// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drmawqsgresxhbjiywbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRybWF3cXNncmVzeGhiaml5d2JwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NTc3NTgsImV4cCI6MjA2OTUzMzc1OH0.Ya4Ibsmbk5G0hVpE_NOy_Kw2YUcUmM0unSYnxvvVmKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});